import { delay } from './apiHelper';
import { AI_CHAT_RESPONSES } from '../../mocks/mockResponses';

export const chatApi = {
  async sendMessage(
    question: string,
    animalContext?: { id: string; tag: string; name: string }
  ): Promise<{ response: string; suggestedFollowUps: string[] }> {
    await delay(1000); // simulated thinking latency

    const q = question.toLowerCase();

    // If context animal is provided
    if (animalContext && (q.includes('this animal') || q.includes('she') || q.includes('her') || q.includes(animalContext.tag.toLowerCase()))) {
      return {
        response: `Regarding **${animalContext.name} (${animalContext.tag})**:
• **Lactation & Production:** Currently in active lactation averaging ~15.2 L/day.
• **Health Status:** Monitored rumination levels are stable. Ensure adequate calcium and chelated mineral mix supplementation.
• **Veterinary Record:** Keep vaccination schedules updated and maintain clean stall bedding.

*Guidance generated by Dairy Nova AI Assistant.*`,
        suggestedFollowUps: [
          `When is ${animalContext.name}'s next vaccination?`,
          `Recommend feed ration for ${animalContext.name}`,
          `Check temperature history`,
        ],
      };
    }

    const matched = AI_CHAT_RESPONSES.find((r) => r.match(q));
    if (matched) {
      return {
        response: matched.response,
        suggestedFollowUps: [
          'Which vaccinations are due this week?',
          'Is my corn silage safe to feed?',
          'How can I increase butterfat percentage?',
        ],
      };
    }

    // General fallback dairy knowledge
    return {
      response: `Thank you for asking! In dairy cattle management, maintaining high-energy dry matter intake (60% quality green fodder, 30% dry roughage, and 10% balanced concentrate pellets) alongside 24/7 ad-libitum clean drinking water is vital for optimal milk production and rumen health.

Is there a specific animal or topic you'd like me to look into?`,
      suggestedFollowUps: [
        'How is my overall herd health?',
        'Show today’s milk collection summary',
        'Analyze my feed quality',
      ],
    };
  },
};
